== Основые понятия

* Сессия (Session) - единица взаимодействия между приложением и БД через Hibernate

* Транзакция - атомарный набор действий внутри бд (начинается с `BEGIN` и заканчивается `COMMIT`)

* Кеш первого уровня - кеш, привязанный к сессии. Если сущность была сохранена в рамках сессии, то при последующем
получении этой сущности, она будет извлечена не из БД, а из этого кеша.

* `session.beginTransaction()` - вызывает команду `BEGIN` в бд.

* `transaction.commit()` - вызывает команду `COMMIT` в бд.

* `session.flush()` - синхронизирует объекты сессии и записи в бд. По сути, выполняет запросы в бд, но без фиксации данных (нужен `commit`)

* `session.clear(0)` - очищает кэш сессии.

* Три состояния объекта в Hibernate - `TRANSIENT`, `PERSISTENT`, `DETACHED`

* [HQL](https://www.tutorialspoint.com/hibernate/hibernate_query_language.htm)

* JPA (набор интерфейсов и аннотации) - стандарт реалации ORM в Java

* EntityManager - менеджер сущностей в JPA

* EntityManagerFactory - фабрика менеджера сущностей.

* LocalContainerEntityManagerFactoryBean - фабрика менеджера сущностей Spring-а

* Spring Data Jpa - работа с JPA/Hibernate внутри Spring

